name: build-goofys
on:
  schedule:
    - cron: '39 22 * * *'
  push:

jobs:
  build:
    strategy:
      runs-on: [ubuntu-latest]
      fail-fast: false
      matrix:
        platform: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      # check out goofys
      - name: Checkout goofys
        uses: actions/checkout@v2
        with:
          repository: kahing/goofys
          path: goofys
      - name: Build Goofys
        env:
          GOOS: ${{ matrix.platform }}
          GOARCH: ${{ matrix.arch }}
        run: |
          cd goofys
          go build -o ../goofys-${{ matrix.platform }}-${{ matrix.arch }}
      - name: Upload Goofys
        uses: actions/upload-artifact@v2
        with:
          name: goofys-${{ matrix.platform }}-${{ matrix.arch }}
          path: goofys-${{ matrix.platform }}-${{ matrix.arch }}