name: build-goofys
on:
  pull_request:
  schedule:
    - cron: '39 22 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout goofys
        uses: actions/checkout@v2
        with:
          repository: kahing/goofys
          path: goofys
          fetch-depth: 0
      - name: Fetch latest tag
        run: |
          cd goofys
          echo "GOOFYS_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      - name: Update gopsutil if running on darwin/arm64
        if: matrix.platform == 'darwin' && matrix.arch == 'arm64'
        run: |
          cd goofys
          go mod edit -replace github.com/shirou/gopsutil=github.com/shirou/gopsutil@v3
          go mod tidy
      - name: Build Goofys
        env:
          GOOS: ${{ matrix.platform }}
          GOARCH: ${{ matrix.arch }}
        run: |
          cd goofys
          go build -o ../goofys-build -ldflags "-X main.Version=${{ env.GOOFYS_VERSION }}"
      - name: Upload Goofys
        uses: actions/upload-artifact@v2
        with:
          name: goofys-${{ env.GOOFYS_VERSION }}-${{ matrix.platform }}-${{ matrix.arch }}
          path: goofys-build
  push-s3:
    runs-on: [ubuntu-latest]
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: goofys
      - name: Upload to S3
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: skyplane-fuse-builds
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: goofys