name: build-goofys
on:
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout goofys
        uses: actions/checkout@v2
        with:
          repository: kahing/goofys
          path: goofys
      - name: Fetch latest tag
        run: |
          cd goofys
          echo "GOOFYS_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      - name: Update gopsutil if running on darwin/arm64
        if: matrix.platform == 'darwin' && matrix.arch == 'arm64'
        run: |
          cd goofys
          go mod edit -replace github.com/shirou/gopsutil=github.com/shirou/gopsutil@v3
          go mod tidy
      - name: Checkout goofys at ${{ env.GOOFYS_VERSION }}
        run: |
          cd goofys
          git checkout ${{ env.GOOFYS_VERSION }}
      - name: Build Goofys
        env:
          GOOS: ${{ matrix.platform }}
          GOARCH: ${{ matrix.arch }}
        run: |
          cd goofys
          go build -o ../goofys
      - name: Upload Goofys
        uses: actions/upload-artifact@v2
        with:
          name: goofys-${{ env.GOOFYS_VERSION }}-${{ matrix.platform }}-${{ matrix.arch }}
          path: goofys